### ISSUE TITLE
1.2.0 not available on cocoapods

### ISSUE THREAD

**Issue by Appsido** [vadymmarkov/Fakery#49]
When i do pod 'Fakery' I keep have the 1.1.2 version. I need to force :path in my pod file. I guess pod spec has not been update in cocoa pods repo ?

Analyzing dependencies
Pre-downloading: `Fakery` from `https://github.com/vadymmarkov/Fakery.git`
Installing Fakery 1.2.0 (was 1.1.2)
Generating Pods project
Integrating client project
Sending stats

**Comment by vadymmarkov** [comment]
@Appsido I've just released v1.3.0 https://github.com/vadymmarkov/Fakery/releases/tag/1.3.0 and it should be available on CocoaPods as well.

**Comment by Appsido** [comment]
I just update my pod as such
**pod 'Fakery'**
As you see I still get the 1.1.2 version.
**Installing Fakery 1.1.2 (was 1.2.0)**

weird.

**Comment by vadymmarkov** [comment]
@Appsido Have you tried to run `pod update`?

**Comment by Appsido** [comment]
Ok it seems that to be an issue with the pod master repo

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     196d681..36f16ba  master     -> origin/master
  error: The following untracked working tree files would be overwritten by merge:
  	Specs/ManageLocalCode/1.0.0/ManageLocalCode.podspec.json
  	Specs/ScalePicker/1.3/ScalePicker.podspec.json
  Please move or remove them before you can merge.
  Aborting
  Updating 3c4d104..36f16ba
